using System.Collections.Generic;

namespace BingoCaller.Utilities;

public static class BingoNameProvider
{
    private static readonly Dictionary<int, string> BingoNames = new()
    {
        { 1, "Kelly's eye" },
        { 2, "One little duck" },
        { 3, "Cup of tea" },
        { 4, "Knock at the door" },
        { 5, "Man alive" },
        { 6, "Tom mix" },
        { 7, "Lucky seven" },
        { 8, "Garden gate" },
        { 9, "Doctor's orders" },
        { 10, "Andy's den" },
        { 11, "Legs eleven" },
        { 12, "One dozen" },
        { 13, "Unlucky for some" },
        { 14, "Valentine's day" },
        { 15, "Young and keen" },
        { 16, "Sweet sixteen" },
        { 17, "Dancing queen" },
        { 18, "Coming of age" },
        { 19, "Goodbye teens" },
        { 20, "One score" },
        { 21, "Key of the door" },
        { 22, "two little ducks" },
        { 23, "Thee and me" },
        { 24, "Two dozen" },
        { 25, "Duck and dive" },
        { 26, "Pick and mix" },
        { 27, "Gateway to heaven" },
        { 28, "In a state" },
        { 29, "Rise and shine" },
        { 30, "Dirty Gertie" },
        { 31, "Get up and run" },
        { 32, "thirty-two" },
        { 33, "all the threes" },
        { 34, "Ask for more" },
        { 35, "Jump and jive" },
        { 36, "thirty-six" },
        { 37, "thirty-seven" },
        { 38, "thirty-eight" },
        { 39, "thirty-nine" },
        { 40, "forty" },
        { 41, "forty-one" },
        { 42, "forty-two" },
        { 43, "forty-three" },
        { 44, "all the fours" },
        { 45, "forty-five" },
        { 46, "forty-six" },
        { 47, "forty-seven" },
        { 48, "forty-eight" },
        { 49, "forty-nine" },
        { 50, "fifty" },
        { 51, "fifty-one" },
        { 52, "fifty-two" },
        { 53, "fifty-three" },
        { 54, "fifty-four" },
        { 55, "all the fives" },
        { 56, "fifty-six" },
        { 57, "fifty-seven" },
        { 58, "fifty-eight" },
        { 59, "fifty-nine" },
        { 60, "sixty" },
        { 61, "sixty-one" },
        { 62, "sixty-two" },
        { 63, "sixty-three" },
        { 64, "sixty-four" },
        { 65, "sixty-five" },
        { 66, "all the sixes" },
        { 67, "sixty-seven" },
        { 68, "sixty-eight" },
        { 69, "sixty-nine" },
        { 70, "seventy" },
        { 71, "seventy-one" },
        { 72, "seventy-two" },
        { 73, "seventy-three" },
        { 74, "seventy-four" },
        { 75, "seventy-five" },
        { 76, "seventy-six" },
        { 77, "all the sevens" },
        { 78, "seventy-eight" },
        { 79, "seventy-nine" },
        { 80, "eighty" },
        { 81, "eighty-one" },
        { 82, "eighty-two" },
        { 83, "eighty-three" },
        { 84, "eighty-four" },
        { 85, "eighty-five" },
        { 86, "eighty-six" },
        { 87, "eighty-seven" },
        { 88, "all the eights" },
        { 89, "eighty-nine" },
        { 90, "ninety" }
    };

    public static string GetBingoName(int number)
    {
        return BingoNames.ContainsKey(number) ? BingoNames[number] : number.ToString();
    }
}
